services:
  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  todo-backend:
    build: ./backend
    image: phavida/todo-backend:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    ports:
      - "15000:15000"
    depends_on:
      - mongo
    restart: unless-stopped

  todo-frontend:
    build: ./frontend
    image: phavida/todo-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
    restart: unless-stopped

volumes:
  mongo_data:
